import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import StickyButton from "../components/StickyButton";

const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Fulusme",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} w-full mx-auto bg-sky`}>
        <Navbar />
        {children}
        <Footer />
        <StickyButton />
      </body>
    </html>
  );
}
