import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import GoogleCaptchaWrapper from "../GoogleCaptchaWrapper";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});
export const metadata: Metadata = {
  title: "Fulusme",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} w-11/12 mx-auto`}>
        <GoogleCaptchaWrapper>{children}</GoogleCaptchaWrapper>
        <Toaster />
      </body>
    </html>
  );
}
