import { getUserData } from "@/lib/auth";
import Nav from "../components/dashboard/Nav";
import Sidebar from "../components/dashboard/Sidebar";
import "../globals.css";
import { Open_Sans } from "next/font/google";
import { UserProvider } from "@/context/UserContext";
import SidebarLinks from "../components/dashboard/SidebarLinks";

const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserData();
  return (
    <html lang="en">
      <body
        className={`${openSans.className} w-full mx-auto min-h-screen bg-[#F4F7FE]`}
      >
        <UserProvider initialUser={user.data}>
          <header className="bg-white">
            <Nav />
          </header>
          <main className="w-4/5 mx-auto my-4 flex flex-col lg:flex-row gap-6">
            <>
              <Sidebar />
            </>
            <div className="block lg:hidden">
              <SidebarLinks />
            </div>

            {children}
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
