import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Fulusme",
  description: "Generated by create next app",
};

export default function KycLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} w-11/12 mx-auto`}>
        {children}
        <a
          href="https://api.whatsapp.com/send?phone=6282299996862&text=Assalamu%27alaikum%2C%0A%0Amohon%20info%20terbaru%20tentang%20Fulusme%20Urun%20Dana"
          className="floating-button flex justify-center items-center gap-2 font-bold rounded-3xl py-3 px-4"
        >
          <img src="/icons/whatsapp.svg" alt="Whatsapp Icon" />
          Butuh Bantuan?
        </a>
      </body>
    </html>
  );
}
